AC: <program>                            = <composite_function_call> | <function_call>
CA: <composite_function_call>            = <target><composite_function>
AC: <composite_function>                 = <chain_composite_function> | <composite_chain_composite_function>
CA: <chain_composite_function>           = .<function_chain>
CA: <composite_chain_composite_function> = <composite_function>.<function_chain>
AC: <function_chain>                     = <function_chains> | <function>
CA: <function_chains>                    = <function_chain><function>
CA: <function_call>                      = <target><function>
AC: <function>                           = <named_arg_function> | <array_access_function>
AC: <named_arg_function>                 = <arg_function> | <no_arg_function>
CA: <no_arg_function>                    = .<name> ()
CA: <arg_function>                       = .<name>(<arg_list>)
CA: <array_access_function>              = \[<sap>\]
AC: <target>                             = <function_call> | <type>
AC: <type>                               = <name> | <type_name>
CA: <type_name>                          = <type>\<name>
AC: <arg_list>                           = <arg> | <args> | <named_arg_list>
CA: <args>                               = <arg>, <arg_list>
CA: <arg>                                = <sap>
AC: <named_arg_list>                     = <named_arg> | <named_args>
CA: <named_args>                         = <named_arg>, <named_arg_list>
CA: <named_arg>                          = <name_nswu> : <sap>
AC: <sap>                                = <scalar> | <array> | <program>
AC: <array>                              = <non_empty_array> | <empty_array>
CA: <non_empty_array>                    = \[ <all_array_entries>\] //TODO: fix this
CA: <empty_array>                        = \[\] //TODO: fix this
AC: <all_array_entries>                  = <pos_array_entry> | <named_array_entry>
AC: <pos_array_entry>                    = <array_entry> | <array_entries>
CA: <array_entries>                      = <array_entry>, <all_array_entries>
CA: <array_entry>                        = <sap>
AC: <named_array_entry>                  = <key_arrow_value> | <named_array_entries>
CA: <named_array_entries>                = <key_arrow_value>, <all_array_entries>
CA: <key_arrow_value>                    = <scalar> => <sap>
AC: <scalar>                             = <bool> | <null> | <num> | <string> | <unsigned_num>
CA: <bool>                               = true | false
CA: <null>                               = null
CA: <name_nswu>                          = [a-zA-Z0-9] | [a-zA-Z0-9]<name>
CA: <name>                               = [a-zA-Z_][A-Za-z0-9_]*
CA: <num>                                = [+-] <unsigned_num>
AC: <unsigned_num>                       = <integer> | <float>
AC: <integer>                            = <octal> | <decimal> | <hexadecimal> | <binary>
AC: <float>                              = <double_number> | <exp_double_number>
CA: <string>                             = *single-quoted-php-string* | *double-quoted-php-string*
CA: <decimal>                            = [0-9]+
CA: <hexadecimal>                        = 0x[0-9A-Fa-f]
CA: <octal>                              = 0[0-7]+
CA: <binary>                             = 0b[0-1]+
CA: <double_number>                      = [0-9]*[\.][0-9]*
CA: <exp_double_number>                  = ([0-9]+|[0-9]*[\.][0-9]*)[eE][+-]?[0-9]+
